global:
  scrape_interval: 5s

scrape_configs:
  - job_name: order-service
    static_configs:
      - targets: ["order-service:8081"]

  - job_name: payment-service
    static_configs:
      - targets: ["payment-service:8082"]

  - job_name: inventory-service
    static_configs:
      - targets: ["inventory-service:8083"]

  - job_name: shipping-service
    static_configs:
      - targets: ["shipping-service:8084"]
